version: '3.8'
services:
  frontend: 
    image: 209591221760.dkr.ecr.eu-west-1.amazonaws.com/frontend
    build: 
      context: ../angular/employee-management-frontend
      dockerfile: pipelines/Dockerfile
      args:
        configuration: development
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - backend

  backend:
    image: 209591221760.dkr.ecr.eu-west-1.amazonaws.com/backend
    build:
      context: ../java/employee-management-backend
      dockerfile: pipelines/Dockerfile
    environment:
      DB_HOST: 'db'
      DB_DBNAME: 'employee_db'
      DB_USERNAME: 'java_app'
      DB_PASSWORD: 'pass123'
      HTTP_PORT: 8081
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'employee_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'java_app'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - database:/var/lib/mysql
# Names our volume
volumes:
  database: