- hosts: jenkins
  user: "{{ server_user }}"
  vars:
    jenkins_admin_password: "{{ jenkins_password }}" 
    private_key: "{{ git_private_key }}"
  become: true
  roles:
    - role: jenkins
    - role: jenkins_jobs
      vars: 
        jenkins_jobs:
          - name: backend
            git_repo: "git@bitbucket.org:andrei_prescornic/docker2kubernetes.git"
            git_folder: "java/**"
            pipeline: "java/employee-management-backend/pipelines/build.groovy"
          - name: frontend
            git_repo: "git@bitbucket.org:andrei_prescornic/docker2kubernetes.git"
            git_folder: "angular/**"
            pipeline: "angular/employee-management-frontend/pipelines/build.groovy"
